apiVersion: v1
kind: Namespace
metadata:
  name: cccns
  labels:
    app: cccapp
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx
  namespace: cccns
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginxsvc
  namespace: cccns
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30008
