apiVersion: v1
kind: PersistentVolume
metadata:
  name: manogpv1
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  nfs:
    server: 10.10.69.175
    path: /opt/nfs
  persistentVolumeReclaimPolicy: Recycle
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: manoghppv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Gi
  hostPath:
    path: /opt/db
  persistentVolumeReclaimPolicy: Recycle
