apiVersion: v1
kind: Namespace
metadata:
  name: test-ns
  labels:
     team: testing
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: rqtestns
  namespace: test-ns
spec:
  hard:
    requests.cpu: "3"
    requests.memory: "3Gi"
    limits.cpu: "3"
    limits.memory: "3Gi"
    pods: "2"
    counts/deployments.apps: "2"
---
apiVersion: v1
kind: LimitRange
metadata: 
  name: lrtestns
  namespace: test-ns
spec:
  limits:
  - default:
      cpu: "2"
      memory: "3Gi"
    defaultRequest:
      cpu: "1"
      memory: "2Gi"
    type: Container
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mavenrq
  namespace: test-ns
spec:
  replicas: 4
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: maven
  template:
    metadata:
      labels:
        app: maven
    spec:
      containers:
        - name: maven
          image: sandeepfile/maven-web-application:1
          ports:
          - containerPort: 8080
          resources:
            requests:
              cpu: 3
              memory: "1Gi"
            limits:
              cpu: 3
              memory: "1Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: mavensvc
  namespace: test-ns
spec:
  type: NodePort
  selector:
    app: maven
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30090
