apiVersion: v1
kind: ConfigMap
metadata:
  name: springapp-config
data:
  MONGO_DB_HOSTNAME: mongosvc
  MONGO_DB_USERNAME: devdb
  MONGO_DB_PASSWORD: devdb@123
---
apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: ZGV2ZGI= # Base64 encoded 'devdb'
  MONGO_INITDB_ROOT_PASSWORD: ZGV2ZGJAMTIz # Base64 encoded 'devdb@123'
