apiVersion: apps/v1
kind: Deployment
metadata:
  name: springappcm
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring
  template:
    metadata:
      labels:
        app: spring
    spec:
      containers:
      - name: springappcon
        image: dockerhandson/spring-boot-mongo:1
        resources:
          requests:
            cpu: 200m
            memory: 100Mi
          limits:
            cpu: 500m
            memory: 200Mi
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: mangocm
---
apiVersion: v1
kind: Service
metadata:
  name: springappsvc
spec:
  type: NodePort
  selector:
    app: spring
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30097
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mangocm
spec:
  selector:
    matchLabels:
      app: mangocm
  template:
    metadata:
      labels:
        app: mangocm
    spec:
      containers:
      - name: mangocontainercm
        image: mongo
        ports:
        - containerPort: 27017
        env:
          - name: MONGOINITDBNAME
            valueFrom:
              configMapKeyRef:
                name: mangocm
                key: MONGO_INITDB_ROOT_USERNAME
          - name: MONGOINITDBPASS
            valueFrom:
              configMapKeyRef:
                name: mangocm
                key: MONGO_INITDB_ROOT_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: mongosvc
spec:
  type: ClusterIP
  selector:
    app: mangocm
  ports:
  - port: 27017
    targetPort: 27017
